[machine]
ram_length = "32Mi"
entrypoint = "/mnt/app/wallet_app"

[drives.root]
builder = "docker"
dockerfile = "Dockerfile"
target = "base"
format = "ext2"
avoid_overwrite = "true"
extra_size = "2Mb"
buildx = true

[drives.app]
builder = "directory"
directory = "build/samples/wallet_app"
format = "sqfs"
