[machine]
ram_length = "32Mi"
entrypoint = "/mnt/app/app /mnt/data/state.bin"
use_docker_env = false # cartesi cli option to avoid using docker rootfs envs
workdir = "/"

[drives.root]
builder = "docker"
dockerfile = "Dockerfile"
target = "base"
format = "ext2"
avoid_overwrite = "true"
extra_size = "2Mb"
buildx = true

[drives.app]
builder = "docker"
dockerfile = "Dockerfile"
target = "app"
format = "sqfs"
buildx = true

[drives.data]
builder = "empty"
size = "34Mb"
format = "ext2"
avoid_overwrite = "true"
user = "dapp"
