name: build-and-release
run-name: Testing and Releasing libcma
on: [push, workflow_dispatch]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    environment: Main

    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Test Ubuntu
        run: |
          make docker ARGS="test"

  build-platforms:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: build
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    strategy:
      fail-fast: false
      matrix:
        images:
          - image: ubuntu
            plat: glibc
          - image: alpine
            plat: musl

    steps:
      - name: Set Envs
        run: |
          echo "VERSION=${GITHUB_REF##*/v}" >> "$GITHUB_ENV"
          echo "TOOLS_TARGZ=${{ vars.TOOLS_TARGZ || 'machine-asset-tools' }}" >> "$GITHUB_ENV"

      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build
        run: |
          mkdir -p artifacts
          ls -la artifacts
          make third-party
          make docker DOCKERFILE=${{ matrix.images.image }}.dockerfile ARGS="tar-files" VERSION=${{ env.VERSION }}
          ls -la build/_tar
          cp build/_tar/machine-asset-tools.tar.gz     artifacts/${{ env.TOOLS_TARGZ }}_${{ matrix.images.plat }}_riscv64_v${{ env.VERSION }}.tar.gz
          cp build/_tar/machine-asset-tools-dev.tar.gz artifacts/${{ env.TOOLS_TARGZ }}_${{ matrix.images.plat }}_riscv64_dev_v${{ env.VERSION }}.tar.gz
          mkdir -p sample_apps/app_cython/.misc
          cp build/_tar/machine-asset-tools* sample_apps/app_cython/.misc/.
          docker build -f sample_apps/app_cython/${{ matrix.images.image }}.dockerfile --platform=linux/riscv64 --target builder -t app_cython_alpine --build-arg MACHINE_ASSET_TOOLS_DEV_TAR=.misc/machine-asset-tools-dev.tar.gz --build-arg MACHINE_ASSET_TOOLS_TAR=.misc/machine-asset-tools.tar.gz --progress plain sample_apps/app_cython
          docker run --rm --platform=linux/riscv64 -v $PWD/artifacts:/mnt/artifacts -u $(id -u):$(id -g) app_cython_alpine cp /opt/build/app/cmpy/cmpy.cpython-*.so /mnt/artifacts/.
      #     make clean
      #     rm -rf sample_apps/app_cython/.misc

      - name: Build Deb
        if: ${{ matrix.images.image }} == 'ubuntu'
        run: |
          make docker DOCKERFILE=ubuntu.dockerfile ARGS="deb" VERSION=${{ env.VERSION }}
          cp build/_deb/machine-asset-tools_riscv64.deb artifacts/${{ env.TOOLS_TARGZ }}_riscv64_v${{ env.VERSION }}.deb

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: cma-${{ matrix.images.plat }}
          path: artifacts/*
          if-no-files-found: error
          retention-days: 1

  release:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Setup
        run: |
          mkdir -p ${{ runner.temp }}/artifacts

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: ${{ runner.temp }}/artifacts
          pattern: cma-*
          merge-multiple: true

      - name: Upload release assets
        uses: softprops/action-gh-release@v2
        with:
          prerelease: true
          files: artifacts/*
          fail_on_unmatched_files: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
