name: build-and-release
run-name: Testing and Releasing libcma
on: [push, workflow_dispatch]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    environment: Main

    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Test Ubuntu
        run: |
          make docker ARGS="test"

  release:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: build-and-test
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Set Envs
        run: |
          echo "VERSION=${GITHUB_REF##*/v}" >> "$GITHUB_ENV"
          echo "TOOLS_TARGZ=${{ vars.TOOLS_TARGZ || 'machine-asset-tools' }}" >> "$GITHUB_ENV"

      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Alpine
        run: |
          mkdir -p artifacts
          ls -la artifacts
          make docker DOCKERFILE=alpine.dockerfile ARGS="tar-files" VERSION=${{ env.VERSION }}
          ls -la build/_tar
          cp build/_tar/machine-asset-tools.tar.gz     artifacts/${{ env.TOOLS_TARGZ }}_musl_riscv64_v${{ env.VERSION }}.tar.gz
          cp build/_tar/machine-asset-tools-dev.tar.gz artifacts/${{ env.TOOLS_TARGZ }}_musl_riscv64_dev_v${{ env.VERSION }}.tar.gz
          mkdir -p sample_apps/app_cython/.misc
          cp build/_tar/machine-asset-tools* sample_apps/app_cython/.misc/.
          docker build -f sample_apps/app_cython/alpine.dockerfile --platform=linux/riscv64 --target builder -t app_cython_alpine --build-arg MACHINE_ASSET_TOOLS_DEV_TAR=.misc/machine-asset-tools-dev.tar.gz --build-arg MACHINE_ASSET_TOOLS_TAR=.misc/machine-asset-tools.tar.gz --progress plain sample_apps/app_cython
          docker run --rm --platform=linux/riscv64 -v $PWD/artifacts:/mnt/artifacts -u $(id -u):$(id -g) app_cython_alpine cp /opt/build/app/cmpy/cmpy.cpython-313-riscv64-linux-musl.so /mnt/artifacts/.
          make clean
          rm -rf sample_apps/app_cython/.misc

      - name: Build Ubuntu
        run: |
          mkdir -p artifacts
          make docker DOCKERFILE=ubuntu.dockerfile ARGS="tar-files" VERSION=${{ env.VERSION }}
          cp build/_tar/machine-asset-tools.tar.gz     artifacts/${{ env.TOOLS_TARGZ }}_glibc_riscv64_v${{ env.VERSION }}.tar.gz
          cp build/_tar/machine-asset-tools-dev.tar.gz artifacts/${{ env.TOOLS_TARGZ }}_glibc_riscv64_dev_v${{ env.VERSION }}.tar.gz
          make docker DOCKERFILE=ubuntu.dockerfile ARGS="deb" VERSION=${{ env.VERSION }}
          cp build/_deb/machine-asset-tools_riscv64.deb artifacts/${{ env.TOOLS_TARGZ }}_riscv64_v${{ env.VERSION }}.deb
          mkdir -p sample_apps/app_cython/.misc
          cp build/_tar/machine-asset-tools* sample_apps/app_cython/.misc/.
          docker build -f sample_apps/app_cython/ubuntu.dockerfile --platform=linux/riscv64 --target builder -t app_cython_ubuntu --build-arg MACHINE_ASSET_TOOLS_DEV_TAR=.misc/machine-asset-tools-dev.tar.gz --build-arg MACHINE_ASSET_TOOLS_TAR=.misc/machine-asset-tools.tar.gz --progress plain sample_apps/app_cython
          docker run --rm --platform=linux/riscv64 -v $PWD/artifacts:/mnt/artifacts -u $(id -u):$(id -g) app_cython_ubuntu cp /opt/build/app/cmpy/cmpy.cpython-313-riscv64-linux-gnu.so /mnt/artifacts/.

      - name: Create sha256sum files
        run: |
          sha256sum artifacts/${{ env.TOOLS_TARGZ }}_musl_riscv64_v${{ env.VERSION }}.tar.gz > artifacts/${{ env.TOOLS_TARGZ }}_musl_riscv64_v${{ env.VERSION }}.tar.gz.sha256
          sha256sum artifacts/${{ env.TOOLS_TARGZ }}_musl_riscv64_dev_v${{ env.VERSION }}.tar.gz > artifacts/${{ env.TOOLS_TARGZ }}_musl_riscv64_dev_v${{ env.VERSION }}.tar.gz.sha256
          sha256sum artifacts/${{ env.TOOLS_TARGZ }}_glibc_riscv64_v${{ env.VERSION }}.tar.gz > artifacts/${{ env.TOOLS_TARGZ }}_glibc_riscv64_v${{ env.VERSION }}.tar.gz.sha256
          sha256sum artifacts/${{ env.TOOLS_TARGZ }}_glibc_riscv64_dev_v${{ env.VERSION }}.tar.gz > artifacts/${{ env.TOOLS_TARGZ }}_glibc_riscv64_dev_v${{ env.VERSION }}.tar.gz.sha256
          sha256sum artifacts/${{ env.TOOLS_TARGZ }}_riscv64_v${{ env.VERSION }}.deb > artifacts/${{ env.TOOLS_TARGZ }}_riscv64_v${{ env.VERSION }}.deb.sha256
          sha256sum artifacts/cmpy.cpython-313-riscv64-linux-musl.so > artifacts/cmpy.cpython-313-riscv64-linux-musl.so.sha256
          sha256sum artifacts/cmpy.cpython-313-riscv64-linux-gnu.so > artifacts/cmpy.cpython-313-riscv64-linux-gnu.so.sha256

      - name: Upload release assets
        uses: softprops/action-gh-release@v2
        with:
          prerelease: true
          files: artifacts/*
          fail_on_unmatched_files: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
